remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: The Strangest Branches
description: an exploration into converging sets of disparate research
show_downloads: false
